Settings:
  Enabled: true
  Start: 2
  Max: 9
  Slots:
    Name: '&c+ Ranura de encantamiento'
    Glow: true
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: NETHER_STAR
    Lore:
    - ' '
    - '&1arrastrar y soltar para añadir una nueva ranura'
