Settings:
  Max: 100
  AutoLevelUpDefault: false
LevelUpEvent:
  '1':
    ShardSlots: 1
    EnchantSlots: 1
    Commands: #spanish version.
    - bc %Player% ha subido de nivel hasta %Level% 
    - give %Player% stone %Level%
