Massage:
  '1': '&e&l(!) Sujeta tu pico'
  '2': '&c Ya está en el nivel máximo!'
  '3': '&c - %Cost% %Currency_Name% %Currency_Symbol% por %NewLevels% levels'
  '4': '&c no tienes el requisito de comprar este Enchant!'
  '5': '&c No tienes ninguna ranura de encantamiento vacía!'
  '6': '&c no tienes suficiente %Currency_Name% %Currency_Symbol%'
  '7': '&c tienes %Currency_Amount% %Currency_Name% %Currency_Symbol%'
  '8': '&c %Player% have %Currency_Amount% %Currency_Name% %Currency_Symbol%'
  '9': '&e&l(!) &eNo tiene el permiso necesario'
  '10': '&e&l(!) &eno tienes suficiente %Currency_Name% %Currency_Symbol% para retirarse'
  '11': '&a&l + %Currency_Amount% %Currency_Name% %Currency_Symbol%'
  '12': '&c&l - %Currency_Amount% %Currency_Name% %Currency_Symbol%'
  '13': '&e&l(!) &epara retirarse.'
  '14': '&e&l(!) &eno puede ser encantado!'
  '15': '&c Su pico es de nivel MAX!'
  '16': '&c La ranura de encantamiento se ha añadido a tu pico!'
  '17': '&c La ranura de esquirlas se ha añadido a tu pico!'
  '18': '&c &eno tienes suficiente energía para subir de nivel!'
  '19': '&c &eSe ha activado la subida de nivel automática'
  '20': '&c &eSe ha desactivado la subida de nivel automática!'
  '21': '&c &etienes una ranura de Enchantment máxima en tu herramienta'
  '22': '&c &etienes una ranura máxima para esquirlas en tu herramienta'
  '23': '&e&l(!) &etienes una ranura máxima para esquirlas en tu herramienta'
  '24': '&c No tienes el requisito de usar este fragmento'
  '25': '&c no puedes permitirte reparar tu pico Costo %Currency_Amount% %Currency_Name%
    %Currency_Symbol%! &e&lintenta suplicar en el chat :) '
  '26': '&c -%Currency_Amount% %Currency_Name% %Currency_Symbol%  '
  '27': '&c &eSe ha habilitado la reparación de automóviles'
  '28': '&c &eLa reparación de automóviles ha sido desactivada!'
  '29': '&c &epor favor, repare su pico! /repair'
  '30': '&c &esu herramienta ya tiene la máxima durabilidad'
  '31': '&c &eSe ha activado el explosivo'
  '32': '&c &eEl explosivo ha sido desactivado!'
  '33': '&c &eJackHammer ha sido activado'
  '34': '&c &eJackHammer ha sido desactivado!'
  '35': '&c &eThorHammer ha sido habilitado'
  '36': '&c &eThorHammer ha sido activado!'
  '37': '&c &eSe ha activado el láser'
  '38': '&c &eEl láser ha sido desactivado!'
